[package]
name         = "syscared"
version      = "1.0.2"
authors      = ["renoseven <dev@renoseven.net>"]
description  = "Syscare daemon"
license      = "MulanPSL-2.0"
edition      = "2021"
rust-version = "1.60"
build        = "build.rs"

[dependencies]
syscare-common     = { package = "syscare-common", path = "../common" }
syscare-abi        = { package = "syscare-abi", path = "../abi" }
anyhow             = { version = "1.0" }
once_cell          = { version = "1.0" }
lazy_static        = { version = "1.0" }
parking_lot        = { version = "0.11" }
indexmap           = { version = "1" }
log                = { version = "0.4" }
flexi_logger       = { version = "0.24", features = ["compress"] }
daemonize          = { version = "0.5.0" }
clap               = { version = "3.2.23", features = ["derive"] }
serde              = { version = "1.0", features = ["derive"] }
inotify            = { version = "0.8" }
jsonrpc-core       = { version = "17.1.0" }
jsonrpc-derive     = { version = "17.1.0" }
jsonrpc-ipc-server = { version = "17.1.0" }
