[package]
name = "upatch-build"
version = "1.0.1"
edition = "2021"
authors = ["lizongwu@huawei.com"]
description = "upatch-build tool"
license = "MulanPSL-2.0"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common", package = "syscare-common"}
log = {version = "0.4"}
object = {version = "0.29.0", features = ["write"]}
gimli = {version = "0.26.1"}
typed-arena = {version = "2.0.1"}
libc = {version = "0.2.137"}
lazy_static = {version = "1.4.0"}
signal-hook = {version = "0.3.14"}
clap = { version = "4.0.32", features = ["derive"] }
which = {version = "4.4.0"}
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "1.3.3" }
memmap2 = {version = "0.5.8"}
memoffset = {version = "0.8.0"}
